# Generated by Django 5.2.8 on 2025-11-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="created_by",
            new_name="user",
        ),
    ]
