# Generated by Django 5.2.8 on 2025-11-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_created_by_project_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
