# Generated by Django 5.2.8 on 2025-11-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_short_description_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.CharField(max_length=255),
        ),
    ]
