# Generated by Django 5.2.8 on 2025-11-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_short_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="thumbnail",
            new_name="thumbnail_dark",
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail_light",
            field=models.URLField(blank=True, null=True),
        ),
    ]
