# Generated by Django 5.2.8 on 2025-11-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_rename_thumbnail_project_thumbnail_dark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="thumbnail_dark_public_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail_light_public_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
