# Generated by Django 5.2.8 on 2025-11-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="completed",
            new_name="done",
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="title",
            new_name="text",
        ),
    ]
