# Generated by Django 5.2.8 on 2025-11-29 03:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("category_name", models.CharField(blank=True, max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de descuento (0-100)",
                        max_digits=4,
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Valoración promedio (0-5)",
                        max_digits=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("out_of_stock", "Sin stock"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "image_public_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
