# Generated by Django 5.2.8 on 2025-11-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_public_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
