# Generated by Django 5.2.8 on 2025-11-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_public_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
